<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <AssemblyName>DragonBoyManager</AssemblyName>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <OutputType>WinExe</OutputType>
    <UseWindowsForms>True</UseWindowsForms>
    <TargetFramework>net48</TargetFramework>
    <Prefer32Bit>True</Prefer32Bit>
  </PropertyGroup>
  <PropertyGroup>
    <LangVersion>7.3</LangVersion>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>
  <PropertyGroup>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <RootNamespace />
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="System.Resources.Extensions" Version="8.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="HardwareID">
        <HintPath>..\Lib\HardwareID.dll</HintPath>
    </Reference>
    <Reference Include="System.Management" />
    <Reference Include="System.Core" />
    <Reference Include="System.Net.Http" />
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
    </None>
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="if not exist &quot;$(MSBuildProjectDirectory)\..\Output&quot; mkdir &quot;$(MSBuildProjectDirectory)\..\Output&quot;&#xD;&#xA;copy /Y &quot;$(TargetPath)&quot; &quot;$(MSBuildProjectDirectory)\..\Output\$(TargetFileName)&quot;&#xD;&#xA;if exist &quot;$(TargetPath).config&quot; copy /Y &quot;$(TargetPath).config&quot; &quot;$(MSBuildProjectDirectory)\..\Output\$(TargetFileName).config&quot;&#xD;&#xA;if not exist &quot;$(MSBuildProjectDirectory)\..\Output\Lib&quot; mkdir &quot;$(MSBuildProjectDirectory)\..\Output\Lib&quot;&#xD;&#xA;copy /Y &quot;$(TargetDir)*.dll&quot; &quot;$(MSBuildProjectDirectory)\..\Output\Lib\&quot;" />
  </Target>
</Project>